FROM node:20-alpine

WORKDIR /app

COPY ui/package*.json ./ui/
WORKDIR /app/ui
RUN npm install

COPY ui .

RUN npm run build

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["npm", "run", "start"]

